name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Update update.json and module.prop
        run: |
          echo '{
            "version": "${{ github.event.inputs.tag }}",
            "versionCode": "${{ steps.get_version.outputs.date }}",
            "zipUrl": "https://github.com/dr05s/clashpro_magisk/releases/download/${{ github.event.inputs.tag }}/clashpro_magisk-${{ github.event.inputs.tag }}.zip",
            "changelog": "https://github.com/dr05s/clashpro_magisk/raw/master/CHANGELOG.md"
          }' > update.json
          sed -i "s/version=$(grep -oP 'version=\K[^ ]+' module.prop)/version=${{ github.event.inputs.tag }}/g" module.prop
          sed -i "s/versionCode=$(grep -oP 'versionCode=\K[^ ]+' module.prop)/versionCode=$(date +%Y%m%d)/g" module.prop
 
      - name: run build.sh
        run: |
          sh build.sh

      - uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          deleteOnlyFromDrafts: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - uses: richardsimko/update-tag@v1.0.11
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: clashpro_magisk-v*.zip
          generate_release_notes: true